import type { SandboxProfile } from './types';

export const BUILTIN_SANDBOX_PROFILES: SandboxProfile[] = [
  {
    id: 'strict-read-only',
    name: 'Strict Read Only',
    description: 'Read-only local and external inspection. No writes, sends, credentials, or process execution.',
    filesystemRoots: [],
    networkAllowlist: [],
    allowedRiskLevels: ['read_only', 'external_read'],
    allowProcessExec: false,
    allowCredentialAccess: false,
    allowExternalSend: false,
    requireApprovalFor: ['external_read'],
  },
  {
    id: 'safe-local-work',
    name: 'Safe Local Work',
    description: 'Read and local write in approved workspace folders.',
    filesystemRoots: ['~'],
    networkAllowlist: [],
    allowedRiskLevels: ['read_only', 'local_write'],
    allowProcessExec: false,
    allowCredentialAccess: false,
    allowExternalSend: false,
    requireApprovalFor: ['local_write'],
  },
  {
    id: 'workspace-write',
    name: 'Workspace Write',
    description: 'Read and write within workspace roots, with destructive actions approval-gated.',
    filesystemRoots: ['~'],
    networkAllowlist: [],
    allowedRiskLevels: ['read_only', 'local_write', 'destructive'],
    allowProcessExec: false,
    allowCredentialAccess: false,
    allowExternalSend: false,
    requireApprovalFor: ['destructive'],
  },
  {
    id: 'external-read',
    name: 'External Read',
    description: 'Allows external reads from approved domains.',
    filesystemRoots: ['~'],
    networkAllowlist: ['https://*'],
    allowedRiskLevels: ['read_only', 'external_read', 'local_write'],
    allowProcessExec: false,
    allowCredentialAccess: false,
    allowExternalSend: false,
    requireApprovalFor: ['external_read', 'local_write'],
  },
  {
    id: 'full-with-approval',
    name: 'Full with Approval',
    description: 'Broad capability surface, but high-risk actions require approval.',
    filesystemRoots: ['~'],
    networkAllowlist: ['https://*'],
    allowedRiskLevels: ['read_only', 'external_read', 'local_write', 'external_write', 'external_send', 'destructive', 'credential_access', 'process_exec'],
    allowProcessExec: false,
    allowCredentialAccess: false,
    allowExternalSend: false,
    requireApprovalFor: ['external_write', 'external_send', 'destructive', 'credential_access', 'process_exec'],
  },
  {
    id: 'development-trusted',
    name: 'Development Trusted',
    description: 'Developer profile for trusted local work. Still approval-gates sends, credentials, and destructive actions.',
    filesystemRoots: ['~'],
    networkAllowlist: ['https://*', 'http://localhost:*'],
    allowedRiskLevels: ['read_only', 'external_read', 'local_write', 'external_write', 'external_send', 'destructive', 'credential_access', 'process_exec'],
    allowProcessExec: true,
    allowCredentialAccess: false,
    allowExternalSend: false,
    requireApprovalFor: ['external_send', 'destructive', 'credential_access'],
  },
];

export function getSandboxProfile(id: string): SandboxProfile {
  return BUILTIN_SANDBOX_PROFILES.find((p) => p.id === id) ?? BUILTIN_SANDBOX_PROFILES[0];
}
