// Built-in workflow templates. Each maps onto existing no-mouse skills/tools.

import type { WorkflowTemplate } from './types';

function step(id: string, title: string, instruction: string, tools?: string[]) {
  return { id, title, instruction, preferredTools: tools };
}

export const BUILT_IN_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'office-email-triage-reply',
    name: 'Email triage and reply draft',
    description: 'Review Gmail, organize messages, and prepare verified reply drafts.',
    source: 'builtin',
    triggerPhrases: ['email triage', 'gmail reply draft', 'emailek atnezese', 'levelek rendszerezese'],
    requiredSkills: ['email-ops'],
    requiredConnections: ['google-workspace'],
    steps: [
      step('s1', 'Search inbox', 'Search Gmail with a bounded query and list matching threads/messages.', ['connection.call']),
      step('s2', 'Read threads', 'Read relevant message bodies or full threads before classification.', ['connection.call']),
      step('s3', 'Organize', 'Suggest or apply labels/archive only to identified message ids.', ['connection.call']),
      step('s4', 'Draft replies', 'Create editable reply drafts in the original threads.', ['email.compose', 'connection.call']),
    ],
    verification: ['Gmail messages/threads were read', 'Draft id or email.compose card exists', 'Any label changes were read back', 'No send occurred without approval'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'office-document-prep',
    name: 'Document search, summary and prep',
    description: 'Find local/Drive/Notion documents, summarize them, and prepare a verified output.',
    source: 'builtin',
    triggerPhrases: ['document prep', 'document summary', 'dokumentum kereses', 'drive summary'],
    requiredSkills: ['document-ops'],
    requiredConnections: [],
    steps: [
      step('s1', 'Resolve sources', 'Search local folders, Drive, Google Docs, or Notion for the requested documents.', ['folder.scan', 'connection.call']),
      step('s2', 'Read sources', 'Read every selected source before summarizing.', ['document.read', 'document.read_many', 'connection.call']),
      step('s3', 'Prepare output', 'Create the requested summary, briefing, Google Doc, DOCX, or PDF.', ['doc.write_docx', 'artifact.render_pdf', 'connection.call']),
    ],
    verification: ['Source list included', 'Output was read back', 'Cloud output metadata/content was read back when used'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'office-system-to-system-copy',
    name: 'System-to-system data copy',
    description: 'Copy data between tools with schema mapping, conflict checks and target read-back.',
    source: 'builtin',
    triggerPhrases: ['copy data between systems', 'adat masolas', 'HubSpot to Sheets', 'Notion to CRM'],
    requiredSkills: ['data-transfer-ops'],
    requiredConnections: [],
    steps: [
      step('s1', 'Read source schema', 'Read source rows/records and infer headers/properties.', ['connection.call', 'sheet.read']),
      step('s2', 'Map target schema', 'Read target metadata and build a field mapping; default conflicts to ask_on_conflict.', ['connection.call', 'sheet.profile']),
      step('s3', 'Write target', 'Write or append approved mapped rows/records.', ['connection.call', 'sheet.write', 'sheet.append']),
      step('s4', 'Verify target', 'Read target rows/records back and compare counts/key fields.', ['connection.call', 'sheet.read']),
    ],
    verification: ['Source count known', 'Target read-back count/key fields match', 'Conflicts were approved or skipped'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'office-client-materials-pack',
    name: 'Client materials pack',
    description: 'Create a proposal, offer, report or summary artifact from client context.',
    source: 'builtin',
    triggerPhrases: ['client materials', 'proposal pack', 'ajanlat keszites', 'ugyfelanyag'],
    requiredSkills: ['client-materials', 'artifact-proposal', 'artifact-business-report'],
    requiredConnections: [],
    steps: [
      step('s1', 'Read context', 'Read brief, project folder, notes or email context.', ['document.read', 'folder.scan', 'connection.call']),
      step('s2', 'Plan material', 'Choose structure, audience, missing assumptions and artifact type.', ['artifact.plan']),
      step('s3', 'Render artifact', 'Render PDF or DOCX from a structured artifact model.', ['artifact.render_pdf', 'artifact.render_docx']),
      step('s4', 'Verify and draft delivery', 'Verify artifact and optionally prepare a delivery email draft.', ['artifact.verify', 'email.compose']),
    ],
    verification: ['Source context read', 'Artifact verify passed', 'Expected client text present', 'Delivery email is draft-only unless approved'],
    scheduleCapable: false,
    eventTriggerCapable: true,
  },
  {
    id: 'office-recurring-admin-run',
    name: 'Recurring admin run',
    description: 'Turn repeated admin work into a safe automation with run evidence.',
    source: 'builtin',
    triggerPhrases: ['recurring admin', 'make this weekly', 'ismetlodo adminisztracio', 'daily admin brief'],
    requiredSkills: ['recurring-admin'],
    requiredConnections: [],
    steps: [
      step('s1', 'Define recurrence', 'Define trigger, input bindings, output target and safety policy.'),
      step('s2', 'Prepare setup', 'Resolve durable folders/docs/sheets/CRM views needed by the automation.', ['connection.call', 'file.write']),
      step('s3', 'Test run', 'Run or simulate the workflow once with visible evidence.', ['workflow.start']),
      step('s4', 'Record verification', 'Write the checklist and blockers for future runs.', ['doc.write_txt']),
    ],
    verification: ['Trigger defined', 'Inputs/outputs bound', 'Safety policy set', 'Test run or blueprint verified'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'office-spreadsheet-refresh',
    name: 'Spreadsheet refresh',
    description: 'Refresh local or Google spreadsheets and verify changed ranges.',
    source: 'builtin',
    triggerPhrases: ['spreadsheet refresh', 'sheet update', 'tablazat frissites', 'Excel refresh'],
    requiredSkills: ['spreadsheet-refresh'],
    requiredConnections: [],
    steps: [
      step('s1', 'Read/profile sheet', 'Read headers, row count, sample rows and formulas.', ['sheet.read', 'sheet.profile', 'connection.call']),
      step('s2', 'Plan update', 'Choose append/update/overwrite and the narrowest target range.'),
      step('s3', 'Apply update', 'Update local or cloud sheet values.', ['sheet.update_cells', 'sheet.append', 'connection.call']),
      step('s4', 'Read changed range', 'Read the affected range back and compare expected values.', ['sheet.read', 'connection.call']),
    ],
    verification: ['Sheet was read before change', 'Changed range was read back', 'Row/column count or expected values match'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'office-meeting-to-actions',
    name: 'Meeting notes to actions',
    description: 'Convert meeting notes into CRM updates, tasks and follow-up email drafts.',
    source: 'builtin',
    triggerPhrases: ['meeting notes to actions', 'CRM update after meeting', 'follow-up email draft', 'meeting jegyzet'],
    requiredSkills: ['meeting-to-actions', 'email-ops'],
    requiredConnections: ['hubspot'],
    steps: [
      step('s1', 'Read notes', 'Read meeting notes or transcript before extracting actions.', ['document.read']),
      step('s2', 'Extract actions', 'Extract decisions, owners, due dates, blockers and next steps.'),
      step('s3', 'Update CRM/task draft', 'Search CRM and create/update notes/tasks only for unambiguous records.', ['connection.call']),
      step('s4', 'Draft follow-up', 'Prepare a follow-up email draft, not a send.', ['email.compose']),
    ],
    verification: ['Action items include owner/due date or explicit unknown', 'CRM/task writes were read back', 'Follow-up draft exists', 'No send without approval'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'office-workspace-maintenance',
    name: 'Workspace maintenance',
    description: 'Audit and maintain Gmail, Drive, Notion, HubSpot and workspace records safely.',
    source: 'builtin',
    triggerPhrases: ['workspace maintenance', 'Drive cleanup', 'Notion database cleanup', 'CRM hygiene'],
    requiredSkills: ['workspace-maintenance'],
    requiredConnections: [],
    steps: [
      step('s1', 'Inventory', 'Run read-only inventory of target workspace surface.', ['connection.call']),
      step('s2', 'Detect issues', 'Find stale, duplicate, missing or misfiled items.'),
      step('s3', 'Approve changes', 'Prepare a change list and request approval for writes.', ['approval.request']),
      step('s4', 'Apply and verify', 'Apply approved changes and read changed items back.', ['connection.call']),
    ],
    verification: ['Read-only audit completed first', 'Approved writes only', 'Changed items read back', 'Maintenance report produced'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'office-microtask-capture',
    name: 'Microtask capture',
    description: 'Turn a repeated 5-15 minute task into a reusable workflow candidate.',
    source: 'builtin',
    triggerPhrases: ['microtask capture', 'turn this into workflow', 'learn this task', 'apro digitalis feladat'],
    requiredSkills: ['microtask-capture'],
    requiredConnections: [],
    steps: [
      step('s1', 'Inspect evidence', 'Use the successful task evidence or ask for missing context.', ['file.read']),
      step('s2', 'Draft workflow', 'Capture trigger, inputs, steps, tools, approvals, outputs and verification.', ['doc.write_txt', 'file.write']),
      step('s3', 'Mark review', 'Save as a review candidate; do not auto-enable without approval.'),
    ],
    verification: ['Workflow candidate includes trigger/inputs/steps/tools/approval/output/verification', 'Saved as draft or review candidate'],
    scheduleCapable: true,
    eventTriggerCapable: true,
  },
  {
    id: 'weekly-marketing-report',
    name: 'Weekly marketing report',
    description: 'Gather metrics from sheets/web and write a summary report.',
    source: 'builtin',
    triggerPhrases: ['weekly marketing report', 'marketing summary'],
    requiredSkills: ['marketing-report'],
    requiredConnections: [],
    steps: [
      step('s1', 'Gather inputs', 'Read the relevant sheets and any linked web sources.', ['sheet.read', 'browser.read']),
      step('s2', 'Aggregate metrics', 'Compute key metrics and week-over-week deltas.'),
      step('s3', 'Write report', 'Write the report as Markdown.', ['file.write']),
    ],
    verification: ['Report file exists and was read back', 'Key metrics present'],
    scheduleCapable: true,
    eventTriggerCapable: false,
  },
  {
    id: 'github-bugfix',
    name: 'GitHub bugfix workflow',
    description: 'Reproduce, fix, test and open a PR for a bug.',
    source: 'builtin',
    triggerPhrases: ['fix bug', 'bugfix', 'open a pr'],
    requiredSkills: ['vscode-project', 'github-maintainer'],
    requiredConnections: ['github'],
    steps: [
      step('s1', 'Locate', 'Find the relevant code with file.search/tree.', ['file.search', 'file.tree']),
      step('s2', 'Fix', 'Make a focused edit.', ['file.edit', 'file.write']),
      step('s3', 'Test', 'Run the tests/build.', ['cli.run']),
      step('s4', 'Summarize diff', 'Show the git diff and summarize it.', ['cli.run']),
    ],
    verification: ['Tests pass', 'Git diff summarized'],
    scheduleCapable: false,
    eventTriggerCapable: true,
  },
  {
    id: 'document-to-spreadsheet',
    name: 'Document to spreadsheet',
    description: 'Extract structured data from documents into a sheet.',
    source: 'builtin',
    triggerPhrases: ['document to spreadsheet', 'extract to sheet'],
    requiredSkills: ['document-accounting', 'local-office'],
    requiredConnections: [],
    steps: [
      step('s1', 'Read documents', 'Read referenced documents.', ['document.read', 'folder.scan']),
      step('s2', 'Extract fields', 'Extract the structured fields.'),
      step('s3', 'Write sheet', 'Write rows to a sheet and read them back.', ['sheet.write', 'sheet.read']),
    ],
    verification: ['Sheet rows match extracted data'],
    scheduleCapable: false,
    eventTriggerCapable: false,
  },
  {
    id: 'meeting-prep',
    name: 'Meeting prep',
    description: 'Compile context and an agenda for an upcoming meeting.',
    source: 'builtin',
    triggerPhrases: ['meeting prep', 'prepare for meeting'],
    requiredSkills: ['google-docs'],
    requiredConnections: ['google-workspace'],
    steps: [
      step('s1', 'Collect context', 'Read relevant docs/notes.', ['document.read', 'connection.call']),
      step('s2', 'Draft agenda', 'Write an agenda document.', ['doc.write_txt', 'connection.call']),
    ],
    verification: ['Agenda document created and read back'],
    scheduleCapable: true,
    eventTriggerCapable: false,
  },
  {
    id: 'competitor-research',
    name: 'Competitor research',
    description: 'Research competitors and summarize with sources.',
    source: 'builtin',
    triggerPhrases: ['competitor research', 'research competitors'],
    requiredSkills: ['browser-automation'],
    requiredConnections: [],
    steps: [
      step('s1', 'Identify', 'Identify the competitors.'),
      step('s2', 'Gather', 'Open and read each source.', ['browser.open', 'browser.read', 'browser.extract_table']),
      step('s3', 'Summarize', 'Write a sourced summary.', ['file.write']),
    ],
    verification: ['Summary cites real sources'],
    scheduleCapable: true,
    eventTriggerCapable: false,
  },
  {
    id: 'file-organization',
    name: 'File organization',
    description: 'Inventory and reorganize a folder with approval for bulk moves.',
    source: 'builtin',
    triggerPhrases: ['organize files', 'clean up folder'],
    requiredSkills: ['file-organizer'],
    requiredConnections: [],
    steps: [
      step('s1', 'Inspect', 'Inventory the folder.', ['file.tree', 'file.list']),
      step('s2', 'Plan', 'Propose a categorization plan.'),
      step('s3', 'Execute', 'Create folders and move files (approval for bulk).', ['file.mkdir', 'file.move']),
    ],
    verification: ['Final folder listing verified'],
    scheduleCapable: false,
    eventTriggerCapable: false,
  },
  {
    id: 'google-sheet-create-verify',
    name: 'Google Sheet creation and verification',
    description: 'Create a cloud Google Sheet, fill it, and verify by reading values back.',
    source: 'builtin',
    triggerPhrases: ['create google sheet', 'google táblázat'],
    requiredSkills: ['google-sheets', 'google-sheets-web'],
    requiredConnections: [],
    steps: [
      step('s1', 'Create/open', 'Create the cloud sheet (connection) or open sheets.new (browser).', ['connection.call', 'browser.open']),
      step('s2', 'Fill', 'Write the values.', ['connection.call', 'browser.paste']),
      step('s3', 'Verify', 'Read the values back / assert cells.', ['connection.call', 'browser.assert_text']),
    ],
    verification: ['Cloud sheet contains the expected rows (not a local file)'],
    scheduleCapable: false,
    eventTriggerCapable: false,
  },
  {
    id: 'landing-page-audit',
    name: 'Landing page audit',
    description: 'Audit a landing page and write findings.',
    source: 'builtin',
    triggerPhrases: ['landing page audit', 'audit page'],
    requiredSkills: ['browser-automation', 'marketing-report'],
    requiredConnections: [],
    steps: [
      step('s1', 'Open', 'Open the page and read content/structure.', ['browser.open', 'browser.read']),
      step('s2', 'Evaluate', 'Check headline, CTA, clarity, load signals.'),
      step('s3', 'Report', 'Write the audit findings.', ['file.write']),
    ],
    verification: ['Audit report written and read back'],
    scheduleCapable: true,
    eventTriggerCapable: false,
  },
];

export function getBuiltInTemplate(id: string): WorkflowTemplate | undefined {
  return BUILT_IN_WORKFLOW_TEMPLATES.find((t) => t.id === id);
}
