import type { ToolRisk } from '../control-system/types';

interface GeneratedSkillSpec {
  name: string;
  description: string;
  categories: string[];
  triggers: string[];
  tools: string[];
  connections?: string[];
  risk: ToolRisk;
  whenToUse: string[];
  whenNotToUse?: string[];
  verification: string[];
}

const READ_FILES = ['file.read', 'file.list', 'file.tree', 'file.search', 'document.read', 'document.read_many', 'folder.scan', 'folder.read_relevant'];
const WRITE_FILES = ['file.write', 'file.edit', 'file.mkdir', 'file.copy', 'file.move', 'file.exists', 'file.list', 'file.tree'];
const LOCAL_OFFICE = ['document.read', 'doc.read', 'doc.write_txt', 'doc.write_docx', 'sheet.read', 'sheet.write', 'sheet.append', 'sheet.export_csv', 'sheet.to_json', 'file.exists'];
const BROWSER = ['browser.open', 'browser.read', 'browser.get_state', 'browser.wait', 'browser.click', 'browser.type', 'browser.key', 'browser.shortcut', 'browser.paste', 'browser.assert_text', 'browser.assert_url', 'browser.extract_table', 'browser.download', 'browser.upload', 'clipboard.set', 'ask_user'];
const CODE = ['file.read', 'file.write', 'file.edit', 'file.search', 'file.tree', 'cli.run'];

const SPECS: GeneratedSkillSpec[] = [
  { name: 'folder-cleanup', description: 'Clean local folders by grouping, renaming, and moving files with a final file-tree proof.', categories: ['files', 'operations'], triggers: ['folder cleanup', 'clean downloads', 'mappa rendezese'], tools: [...READ_FILES, ...WRITE_FILES, 'approval.request'], risk: 'local_write', whenToUse: ['Use for broad local folder cleanup and deterministic organization.'], verification: ['Read the final source and destination folder tree after moving files.', 'Write or report an operation log with changed paths.'] },
  { name: 'document-reader', description: 'Read, summarize, and extract facts from local files, folders, PDFs, docs, and text references.', categories: ['documents'], triggers: ['read document', 'pdf olvasas', 'document extraction'], tools: READ_FILES, risk: 'read_only', whenToUse: ['Use when the user asks to understand referenced documents.'], verification: ['Confirm every referenced file or selected folder item was actually read.', 'Separate extracted facts from uncertainty.'] },
  { name: 'invoice-extractor', description: 'Extract invoice fields from referenced documents into structured rows.', categories: ['documents', 'accounting'], triggers: ['invoice extractor', 'szamla kivonatolas', 'bizonylat'], tools: [...READ_FILES, 'sheet.write', 'sheet.read', 'file.write'], risk: 'local_write', whenToUse: ['Use for invoice or receipt field extraction.'], verification: ['Read source invoice documents before extraction.', 'Read back the output table or JSON after writing.'] },
  { name: 'receipt-processor', description: 'Process receipts into normalized expense rows with vendor, date, tax, total, and category.', categories: ['documents', 'accounting'], triggers: ['receipt', 'nyugta', 'expense'], tools: [...READ_FILES, 'sheet.write', 'sheet.read'], risk: 'local_write', whenToUse: ['Use for receipts, expense evidence, or small purchase documents.'], verification: ['Read each receipt before creating rows.', 'Read back totals and row count from the output.'] },
  { name: 'spreadsheet-builder', description: 'Build local spreadsheets and CSVs from user-provided or extracted data.', categories: ['data', 'office'], triggers: ['build spreadsheet', 'xlsx keszites', 'csv table'], tools: LOCAL_OFFICE, risk: 'local_write', whenToUse: ['Use when the target is a local XLSX or CSV.'], whenNotToUse: ['Do not use for cloud Google Sheets requests.'], verification: ['Read the created spreadsheet back with sheet.read or sheet.to_json.'] },
  { name: 'csv-cleaner', description: 'Clean, normalize, deduplicate, and rewrite CSV data with read-back checks.', categories: ['data'], triggers: ['clean csv', 'csv tisztitas', 'deduplicate rows'], tools: ['file.read', 'file.write', 'sheet.read', 'sheet.write', 'sheet.to_json'], risk: 'local_write', whenToUse: ['Use for local CSV cleanup and normalization.'], verification: ['Read the source CSV before editing.', 'Read the cleaned CSV or sheet rows after writing.'] },
  { name: 'xlsx-reporter', description: 'Create local XLSX reports with summary rows and source-backed metrics.', categories: ['data', 'reporting'], triggers: ['xlsx report', 'excel riport', 'weekly report'], tools: LOCAL_OFFICE, risk: 'local_write', whenToUse: ['Use for local Excel-style report generation.'], verification: ['Read input data first.', 'Read the final XLSX rows after writing.'] },
  { name: 'docx-writer', description: 'Write local DOCX or text documents from structured content and verify the file.', categories: ['documents', 'office'], triggers: ['write docx', 'word dokumentum', 'document draft'], tools: ['doc.write_docx', 'doc.write_txt', 'document.read', 'doc.read', 'file.exists'], risk: 'local_write', whenToUse: ['Use when the user wants a local document file.'], verification: ['Confirm the file exists.', 'Read the generated document content back.'] },
  { name: 'pdf-creator', description: 'Prepare PDF-ready local content and exports through available document tools.', categories: ['documents', 'office'], triggers: ['create pdf', 'pdf keszites', 'export pdf'], tools: ['doc.write_txt', 'doc.write_docx', 'file.exists', 'document.read', 'connection.call', 'ask_user'], risk: 'local_write', whenToUse: ['Use when the user asks for a PDF artifact or PDF-ready document.'], verification: ['Confirm the produced file exists or the export provider returned a file id.', 'Read back the source/exported content where possible.'] },
  { name: 'pdf-extractor', description: 'Extract text, tables, and key values from PDFs without screenshots or visual clicks.', categories: ['documents'], triggers: ['pdf extract', 'pdf tabla', 'pdf kivonatolas'], tools: ['document.read', 'document.read_many', 'folder.read_relevant', 'file.write'], risk: 'local_write', whenToUse: ['Use for PDF text or table extraction.'], verification: ['Read the PDF through document tools.', 'Verify extracted text or table rows in the output.'] },
  { name: 'folder-watch-processor', description: 'Process new folder files from automation payloads and write verified outputs.', categories: ['automation', 'files'], triggers: ['folder watch', 'new file automation', 'mappa figyeles'], tools: [...READ_FILES, 'sheet.append', 'sheet.read', 'file.write', 'file.exists'], risk: 'local_write', whenToUse: ['Use inside automations triggered by new or changed files.'], verification: ['Use the trigger payload path, not a guessed file.', 'Read the updated output after processing.'] },
  { name: 'archive-and-backup', description: 'Archive, copy, and back up files with explicit destination verification.', categories: ['files', 'operations'], triggers: ['archive files', 'backup folder', 'mentes'], tools: ['file.list', 'file.tree', 'file.copy', 'file.mkdir', 'file.exists', 'file.metadata', 'approval.request'], risk: 'local_write', whenToUse: ['Use for non-destructive archive and backup flows.'], verification: ['Confirm copied files exist at destination.', 'List the backup destination after copy.'] },

  { name: 'google-drive', description: 'Find, create, move, export, and verify Google Drive files through Google Workspace.', categories: ['google-workspace'], triggers: ['google drive', 'drive file', 'google fajl'], tools: ['connection.call', 'ask_user'], connections: ['google-workspace'], risk: 'external_write', whenToUse: ['Use for Google Drive file operations.'], verification: ['Read back Drive metadata or search results after changes.'] },
  { name: 'gmail-draft-and-send', description: 'Draft, review, and send Gmail messages only through configured Google Workspace.', categories: ['google-workspace', 'email'], triggers: ['gmail draft', 'send email', 'email kuldes'], tools: ['connection.call', 'approval.request', 'ask_user'], connections: ['google-workspace'], risk: 'external_send', whenToUse: ['Use for Gmail drafts and sends.'], verification: ['Create a draft before sending when possible.', 'Read back draft/message status or provider id after send.'] },
  { name: 'gmail-inbox-triage', description: 'Search and summarize Gmail inbox items without exposing credentials.', categories: ['google-workspace', 'email'], triggers: ['gmail triage', 'inbox summarize', 'email rendezes'], tools: ['connection.call', 'ask_user'], connections: ['google-workspace'], risk: 'external_read', whenToUse: ['Use for inbox search, labels, and summaries.'], verification: ['Read matching messages or label metadata from Gmail.'] },
  { name: 'google-calendar-scheduler', description: 'Create and update Google Calendar events with conflict checks and read-back.', categories: ['google-workspace', 'calendar'], triggers: ['calendar event', 'meeting schedule', 'naptar'], tools: ['connection.call', 'approval.request', 'ask_user'], connections: ['google-workspace'], risk: 'external_write', whenToUse: ['Use for Google Calendar scheduling.'], verification: ['Read the created or updated event back.'] },
  { name: 'google-workspace-reporting', description: 'Compile reports from Google Docs, Sheets, Drive, Gmail, or Calendar data.', categories: ['google-workspace', 'reporting'], triggers: ['google workspace report', 'drive report', 'sheets report'], tools: ['connection.call', 'doc.write_txt', 'file.write'], connections: ['google-workspace'], risk: 'external_read', whenToUse: ['Use for reports sourced from Google Workspace.'], verification: ['Read provider data first.', 'Read the final report file or doc back.'] },

  { name: 'web-research', description: 'Research web pages with browser DOM reading and source-grounded summaries.', categories: ['browser', 'research'], triggers: ['web research', 'online kutatas', 'find sources'], tools: ['browser.open', 'browser.read', 'browser.extract_table', 'file.write'], risk: 'external_read', whenToUse: ['Use when the user asks to gather current web information.'], verification: ['Open and read each cited source page.', 'Keep claims tied to source URLs.'] },
  { name: 'website-table-extractor', description: 'Extract web tables into structured rows or local CSV/XLSX files.', categories: ['browser', 'data'], triggers: ['extract website table', 'web tabla', 'scrape table'], tools: ['browser.open', 'browser.read', 'browser.extract_table', 'sheet.write', 'sheet.read', 'file.write'], risk: 'local_write', whenToUse: ['Use for DOM-accessible web tables.'], verification: ['Extract via browser.extract_table or DOM read.', 'Read the saved table back.'] },
  { name: 'form-filler', description: 'Fill web forms through labels/selectors and verify submitted state.', categories: ['browser'], triggers: ['fill form', 'urlap kitoltes', 'submit form'], tools: BROWSER, risk: 'external_write', whenToUse: ['Use for accessible browser form workflows.'], verification: ['Read the page after submission.', 'Assert confirmation text or URL when possible.'] },
  { name: 'download-manager', description: 'Download files through the browser and verify local saved paths.', categories: ['browser', 'files'], triggers: ['download file', 'letoltes', 'save download'], tools: ['browser.open', 'browser.read', 'browser.download', 'file.exists', 'file.move', 'file.metadata', 'file.list'], risk: 'local_write', whenToUse: ['Use for browser downloads and post-download placement.'], verification: ['Confirm the saved path exists.', 'List or read metadata after moving the file.'] },
  { name: 'browser-login-helper', description: 'Handle browser sign-in using saved credentials or manual handoff.', categories: ['browser', 'credentials'], triggers: ['login', 'sign in', 'belepes'], tools: ['browser.open', 'browser.read', 'browser.login', 'browser.wait', 'ask_user'], risk: 'credential_access', whenToUse: ['Use when a browser workflow reaches a login page.'], verification: ['Read the page after login attempt.', 'Ask user for 2FA/CAPTCHA/manual blocker.'] },
  { name: 'webapp-readback-verifier', description: 'Verify browser/webapp changes through DOM reads, assertions, URLs, and tables.', categories: ['browser', 'safety'], triggers: ['verify webapp', 'read back website', 'ellenorizd web'], tools: ['browser.read', 'browser.get_state', 'browser.assert_text', 'browser.assert_url', 'browser.extract_table'], risk: 'external_read', whenToUse: ['Use after browser changes before completion.'], verification: ['Capture concrete text, URL, or table evidence from the webapp.'] },

  { name: 'repo-auditor', description: 'Audit a local repository and produce grounded improvement recommendations.', categories: ['development'], triggers: ['repo audit', 'audit repository', 'repo atnezes'], tools: [...CODE, 'file.write'], risk: 'read_only', whenToUse: ['Use for repository analysis and recommendations.'], verification: ['Read relevant files before making claims.', 'Ground findings in file paths or command output.'] },
  { name: 'code-reviewer', description: 'Review code changes for bugs, regressions, missing tests, and risky behavior.', categories: ['development'], triggers: ['code review', 'review pr', 'kod review'], tools: ['file.read', 'file.search', 'cli.run'], risk: 'read_only', whenToUse: ['Use for code review stance.'], verification: ['Inspect diffs/files and cite file paths.', 'Prioritize findings before summary.'] },
  { name: 'test-runner', description: 'Run focused tests and summarize failures with next actions.', categories: ['development'], triggers: ['run tests', 'test failure', 'vitest'], tools: ['cli.run', 'file.read', 'file.search'], risk: 'process_exec', whenToUse: ['Use when the user asks to run or debug tests.'], verification: ['Report the exact command and exit result.', 'Read relevant failure output.'] },
  { name: 'bug-fixer', description: 'Diagnose, edit, and verify focused bug fixes in local code.', categories: ['development'], triggers: ['fix bug', 'hiba javitas', 'regression'], tools: CODE, risk: 'process_exec', whenToUse: ['Use for implementation bug fixes.'], verification: ['Run focused tests or explain why unavailable.', 'Inspect the changed diff before completion.'] },
  { name: 'dependency-updater', description: 'Review and update dependencies with lockfile and test verification.', categories: ['development'], triggers: ['update dependency', 'npm update', 'package upgrade'], tools: ['file.read', 'file.edit', 'cli.run'], risk: 'process_exec', whenToUse: ['Use for dependency updates.'], verification: ['Run install/build/tests appropriate to the update.', 'Check changed lockfile/package files.'] },
  { name: 'release-notes', description: 'Draft release notes from commits, diffs, issues, or provided context.', categories: ['development', 'content'], triggers: ['release notes', 'changelog', 'kiadasi jegyzet'], tools: ['cli.run', 'file.read', 'file.search', 'file.write'], risk: 'local_write', whenToUse: ['Use for changelogs and release summaries.'], verification: ['Read source commits/diffs/context.', 'Read the generated notes back.'] },
  { name: 'pull-request-writer', description: 'Create clear pull request summaries, test plans, and risk notes from local diffs.', categories: ['development'], triggers: ['write pr', 'pull request description', 'pr summary'], tools: ['cli.run', 'file.read', 'file.write'], risk: 'local_write', whenToUse: ['Use for PR descriptions and summaries.'], verification: ['Inspect git diff or changed files.', 'Include tests run or not run.'] },
  { name: 'security-auditor', description: 'Audit code/config for security issues without reading unrelated secrets.', categories: ['development', 'security'], triggers: ['security audit', 'secret leak', 'rls audit'], tools: ['file.read', 'file.search', 'cli.run'], risk: 'read_only', whenToUse: ['Use for security reviews and hardening advice.'], verification: ['Avoid printing secrets.', 'Ground findings in files and evidence.'] },
  { name: 'architecture-reviewer', description: 'Review architecture, module boundaries, and technical direction from repo evidence.', categories: ['development', 'architecture'], triggers: ['architecture review', 'system design', 'architektura'], tools: ['file.read', 'file.search', 'file.tree'], risk: 'read_only', whenToUse: ['Use for architecture review.'], verification: ['Read relevant docs/code before recommendations.'] },
  { name: 'frontend-reviewer', description: 'Review frontend UI code for behavior, layout, accessibility, and state bugs.', categories: ['development', 'frontend'], triggers: ['frontend review', 'ui bug', 'react review'], tools: ['file.read', 'file.search', 'cli.run'], risk: 'read_only', whenToUse: ['Use for frontend code review.'], verification: ['Cite component files and tests.'] },
  { name: 'backend-reviewer', description: 'Review backend/server code, APIs, persistence, jobs, and error handling.', categories: ['development', 'backend'], triggers: ['backend review', 'api bug', 'server review'], tools: ['file.read', 'file.search', 'cli.run'], risk: 'read_only', whenToUse: ['Use for backend code review.'], verification: ['Cite code paths and runtime risks.'] },
  { name: 'database-designer', description: 'Design database schemas, migrations, constraints, and query verification plans.', categories: ['development', 'database'], triggers: ['database schema', 'migration', 'postgres design'], tools: ['file.read', 'file.write', 'file.search', 'cli.run'], risk: 'local_write', whenToUse: ['Use for database schema work.'], verification: ['Inspect existing migrations/schema.', 'Run or explain migration/test verification.'] },
  { name: 'api-designer', description: 'Design API contracts, request/response schemas, errors, and tests.', categories: ['development', 'api'], triggers: ['api design', 'endpoint', 'openapi'], tools: ['file.read', 'file.write', 'file.search'], risk: 'local_write', whenToUse: ['Use for API contract design.'], verification: ['Check existing API patterns.', 'Verify docs or tests reflect the contract.'] },

  { name: 'content-production', description: 'Produce structured content drafts with SEO, audience, and quality checks.', categories: ['marketing', 'content'], triggers: ['blog post', 'content production', 'seo cikk', 'article draft'], tools: ['file.write', 'file.read', 'browser.open', 'browser.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for blog posts, articles, and long-form content drafts.'], verification: ['Include outline, draft, meta title/description, and quality checklist.', 'Read saved draft back if written to file.'] },
  { name: 'content-strategy', description: 'Plan content themes, channels, briefs, and calendars from goals and context.', categories: ['marketing', 'content'], triggers: ['content strategy', 'editorial plan', 'tartalom strategia'], tools: ['file.write', 'file.read', 'browser.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for content planning and briefs.'], verification: ['Tie strategy to audience, goals, and channels.', 'Read saved plan back if written.'] },
  { name: 'content-repurposing', description: 'Convert existing content into channel-specific variants with source fidelity.', categories: ['marketing', 'content'], triggers: ['repurpose content', 'social snippets', 'tartalom ujrahasznositas'], tools: ['document.read', 'file.read', 'file.write'], risk: 'local_write', whenToUse: ['Use to turn one asset into multiple formats.'], verification: ['Read the source content first.', 'Verify each requested output format is present.'] },
  { name: 'seo-audit', description: 'Audit SEO structure, metadata, search intent, and page content from readable sources.', categories: ['marketing', 'seo'], triggers: ['seo audit', 'technical seo', 'seo ellenorzes'], tools: ['browser.open', 'browser.read', 'file.read', 'file.write'], risk: 'local_write', whenToUse: ['Use for SEO audits and recommendations.'], verification: ['Read page/source content before recommendations.', 'Include prioritized issues and evidence.'] },
  { name: 'aeo-audit', description: 'Audit answer-engine optimization for concise answers, entities, schema, and citations.', categories: ['marketing', 'seo'], triggers: ['aeo audit', 'answer engine', 'ai search'], tools: ['browser.open', 'browser.read', 'file.write'], risk: 'local_write', whenToUse: ['Use for AEO or AI-search readiness audits.'], verification: ['Read current page/source.', 'Provide concrete answer blocks and schema suggestions.'] },
  { name: 'landing-page-copy', description: 'Write landing-page copy with hero, sections, CTAs, objections, and proof.', categories: ['marketing', 'copywriting'], triggers: ['landing page', 'hero copy', 'weboldal szoveg'], tools: ['file.write', 'file.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for landing page messaging and conversion copy.'], verification: ['Include hero, CTA, proof, objections, and SEO basics.', 'Read saved copy back if written.'] },
  { name: 'competitor-intel', description: 'Research competitors through web reads and produce a grounded comparison.', categories: ['marketing', 'research'], triggers: ['competitor intel', 'versenytars elemzes', 'market research'], tools: ['browser.open', 'browser.read', 'file.write'], risk: 'external_read', whenToUse: ['Use for competitor research and positioning.'], verification: ['Read competitor pages directly.', 'Distinguish observed facts from inference.'] },
  { name: 'social-content', description: 'Create social post variants for channels with source-aware messaging.', categories: ['marketing', 'social'], triggers: ['social content', 'linkedin post', 'facebook poszt'], tools: ['file.write', 'file.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for drafting social content, not publishing.'], verification: ['Produce variants per requested channel.', 'Do not publish unless explicitly asked and connected.'] },
  { name: 'email-campaign', description: 'Draft email campaign strategy, copy, segments, and send-readiness checks.', categories: ['marketing', 'email'], triggers: ['email campaign', 'newsletter', 'kampany email'], tools: ['file.write', 'file.read', 'connection.call', 'approval.request', 'ask_user'], risk: 'external_send', whenToUse: ['Use for email campaign drafting or connected sends.'], verification: ['Read source/brief first.', 'Require approval and provider confirmation before sends.'] },
  { name: 'brand-voice-analyzer', description: 'Analyze brand voice from source materials and produce reusable guidance.', categories: ['marketing', 'brand'], triggers: ['brand voice', 'tone analysis', 'markahang'], tools: ['document.read', 'file.read', 'browser.read', 'file.write'], risk: 'local_write', whenToUse: ['Use for brand voice analysis and style guides.'], verification: ['Read representative source samples.', 'Include do/dont examples grounded in samples.'] },
  { name: 'customer-success-manager', description: 'Plan customer success workflows, health checks, playbooks, and communications.', categories: ['business', 'ops'], triggers: ['customer success', 'cs playbook', 'ugyfel siker'], tools: ['file.write', 'file.read', 'connection.call', 'ask_user'], risk: 'local_write', whenToUse: ['Use for CS process and communication artifacts.'], verification: ['Include owner, trigger, action, and proof for each playbook step.'] },
  { name: 'revenue-operations', description: 'Map revenue workflows, CRM fields, reporting needs, and operational fixes.', categories: ['business', 'ops'], triggers: ['revops', 'sales ops', 'revenue operations'], tools: ['file.write', 'file.read', 'sheet.read', 'connection.call'], risk: 'local_write', whenToUse: ['Use for revenue process and reporting work.'], verification: ['Ground recommendations in read data or clearly mark assumptions.'] },
  { name: 'proposal-writer', description: 'Draft proposals with scope, deliverables, timeline, pricing assumptions, and risks.', categories: ['business', 'content'], triggers: ['proposal', 'ajanlat', 'scope of work'], tools: ['file.write', 'file.read', 'document.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for business proposals and SOW drafts.'], verification: ['Include scope, assumptions, exclusions, and next steps.', 'Read saved proposal back if written.'] },
  { name: 'rfp-responder', description: 'Answer RFP requirements with compliance matrix and evidence-backed responses.', categories: ['business', 'content'], triggers: ['rfp', 'tender response', 'palyazat'], tools: ['document.read', 'file.read', 'file.write', 'ask_user'], risk: 'local_write', whenToUse: ['Use for RFP response drafting.'], verification: ['Read RFP/source docs.', 'Map each requirement to a response or blocker.'] },
  { name: 'sales-engineer', description: 'Create technical sales answers, demos, solution maps, and implementation notes.', categories: ['business', 'technical'], triggers: ['sales engineer', 'technical sales', 'solution brief'], tools: ['file.read', 'file.write', 'browser.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for technical sales collateral.'], verification: ['Tie claims to product/repo/source evidence when available.'] },

  { name: 'product-manager', description: 'Turn goals into product decisions, priorities, requirements, and tradeoffs.', categories: ['product'], triggers: ['product manager', 'feature plan', 'prioritize'], tools: ['file.read', 'file.write', 'ask_user'], risk: 'local_write', whenToUse: ['Use for product planning and prioritization.'], verification: ['Include user, problem, success metric, and tradeoffs.'] },
  { name: 'prd-writer', description: 'Write PRDs with problem, goals, non-goals, user stories, requirements, and acceptance criteria.', categories: ['product'], triggers: ['prd', 'product requirements', 'spec iras'], tools: ['file.write', 'file.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for PRD/spec creation.'], verification: ['Include acceptance criteria and open questions.', 'Read saved PRD back if written.'] },
  { name: 'roadmap-planner', description: 'Build roadmap plans with milestones, dependencies, risks, and sequencing.', categories: ['product', 'project'], triggers: ['roadmap', 'milestone plan', 'utemezes'], tools: ['file.write', 'file.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for roadmap planning.'], verification: ['Include phases, dependencies, risks, and measurable outcomes.'] },
  { name: 'ux-researcher', description: 'Plan UX research, synthesize notes, and produce findings with evidence.', categories: ['product', 'research'], triggers: ['ux research', 'user interview', 'kutatasi terv'], tools: ['document.read', 'file.read', 'file.write', 'ask_user'], risk: 'local_write', whenToUse: ['Use for UX research plans and synthesis.'], verification: ['Separate direct observations from interpretation.'] },
  { name: 'project-manager', description: 'Create project plans, task breakdowns, owners, dates, and status reports.', categories: ['project', 'ops'], triggers: ['project plan', 'task breakdown', 'projekt'], tools: ['file.write', 'file.read', 'connection.call', 'ask_user'], risk: 'local_write', whenToUse: ['Use for project planning and coordination docs.'], verification: ['Include owner, due date, dependency, and status for tasks.'] },
  { name: 'scrum-master', description: 'Prepare agile ceremonies, sprint plans, retrospectives, and impediment lists.', categories: ['project'], triggers: ['scrum', 'sprint planning', 'retro'], tools: ['file.write', 'file.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for agile ceremony support.'], verification: ['Include clear actions, owners, and blockers.'] },
  { name: 'jira-workflow', description: 'Plan or update Jira-style issue workflows through available connections or local docs.', categories: ['project', 'ops'], triggers: ['jira', 'issue workflow', 'ticket'], tools: ['connection.call', 'file.write', 'file.read', 'ask_user'], risk: 'external_write', whenToUse: ['Use for Jira workflows when connected or documented locally.'], verification: ['Read back issue/status when using a provider.', 'Otherwise produce a local plan only.'] },
  { name: 'confluence-docs', description: 'Create or structure Confluence-style documentation with read-back requirements.', categories: ['project', 'docs'], triggers: ['confluence', 'wiki docs', 'documentation page'], tools: ['connection.call', 'file.write', 'file.read', 'ask_user'], risk: 'external_write', whenToUse: ['Use for Confluence documentation workflows.'], verification: ['Read back provider page or saved local doc.'] },
  { name: 'slack-operations', description: 'Draft or send Slack updates, reminders, and operational summaries with approval.', categories: ['ops'], triggers: ['slack update', 'team message', 'ertesites'], tools: ['connection.call', 'approval.request', 'file.write', 'ask_user'], risk: 'external_send', whenToUse: ['Use for Slack operational messages.'], verification: ['Draft before sending.', 'Read provider confirmation after send.'] },
  { name: 'process-mapper', description: 'Map business processes, inputs, outputs, owners, risks, and automation candidates.', categories: ['ops'], triggers: ['process map', 'workflow map', 'folyamat'], tools: ['file.write', 'file.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for process mapping and SOP drafts.'], verification: ['Include trigger, owner, steps, outputs, and failure modes.'] },
  { name: 'knowledge-ops', description: 'Organize knowledge bases, FAQs, SOPs, and source-backed documentation.', categories: ['ops', 'docs'], triggers: ['knowledge base', 'faq', 'sop'], tools: ['document.read', 'file.read', 'file.write', 'connection.call'], risk: 'local_write', whenToUse: ['Use for knowledge organization and docs.'], verification: ['Read source materials first.', 'Read saved/created documentation back.'] },
  { name: 'vendor-management', description: 'Track vendors, renewals, contacts, documents, and decision notes.', categories: ['ops', 'business'], triggers: ['vendor', 'supplier', 'beszallito'], tools: ['file.read', 'file.write', 'sheet.read', 'sheet.write', 'sheet.read'], risk: 'local_write', whenToUse: ['Use for vendor tracking and summaries.'], verification: ['Read source contract/invoice data.', 'Read updated tracker back.'] },

  { name: 'skill-router', description: 'Diagnose task intent and select skill chains with missing requirement blockers.', categories: ['meta', 'safety'], triggers: ['skill router', 'choose skill', 'route task'], tools: ['skill.run', 'ask_user'], risk: 'read_only', whenToUse: ['Use to explain or test skill selection.'], verification: ['Return selected skill names, reasons, confidence, and blockers.'] },
  { name: 'workflow-builder', description: 'Design reusable workflows from triggers, steps, tools, and verification checks.', categories: ['meta', 'automation'], triggers: ['build workflow', 'workflow template', 'folyamat automatizalas'], tools: ['workflow.start', 'file.write', 'file.read', 'ask_user'], risk: 'local_write', whenToUse: ['Use for workflow design.'], verification: ['Include trigger, inputs, actions, blockers, and evidence checks.'] },
  { name: 'automation-designer', description: 'Design automations with trigger payloads, attached skills, connection checks, and verification.', categories: ['meta', 'automation'], triggers: ['automation design', 'automacio', 'folder trigger'], tools: ['file.write', 'file.read', 'workflow.start', 'ask_user'], risk: 'local_write', whenToUse: ['Use for automation planning/building.'], verification: ['Validate required connections before run.', 'Define read-back proof after automation actions.'] },
  { name: 'approval-planner', description: 'Plan approvals for risky, destructive, external-send, and credential workflows.', categories: ['meta', 'safety'], triggers: ['approval plan', 'risk approval', 'engedely'], tools: ['approval.request', 'file.write', 'ask_user'], risk: 'read_only', whenToUse: ['Use when a workflow needs approval gates.'], verification: ['List risk, proposed action, required approval, and audit proof.'] },
  { name: 'safe-data-handling', description: 'Handle sensitive data with minimization, redaction, no credential exposure, and audit notes.', categories: ['meta', 'safety'], triggers: ['safe data', 'sensitive data', 'credential safety'], tools: ['file.read', 'file.write', 'ask_user'], risk: 'credential_access', whenToUse: ['Use when tasks mention secrets, credentials, or sensitive records.'], verification: ['Do not print secrets.', 'Document redaction/minimization decisions.'] },
  { name: 'manual-handoff', description: 'Create clear manual handoff steps for auth, CAPTCHA, permissions, or unavailable tools.', categories: ['meta', 'safety'], triggers: ['manual handoff', 'blocked', 'captcha', 'permission'], tools: ['ask_user', 'file.write'], risk: 'read_only', whenToUse: ['Use when automation is blocked by human-only steps.'], verification: ['State what was tried, what is blocked, and the exact user action needed.'] },
];

function list(items: string[]): string {
  return `[${items.map((item) => JSON.stringify(item)).join(', ')}]`;
}

function skillMarkdown(spec: GeneratedSkillSpec): string {
  const body = [
    `# ${spec.name}`,
    spec.description,
    '',
    '## When to use',
    ...spec.whenToUse.map((item) => `- ${item}`),
    '',
    '## When not to use',
    ...(spec.whenNotToUse?.length ? spec.whenNotToUse : ['Do not use when another skill exactly matches the requested surface or connection.'])
      .map((item) => `- ${item}`),
    '- Do not use mouse, cursor, screenshot, OCR-click, coordinates, or pixel fallback.',
    '',
    '## Workflow',
    '1. Confirm the requested target surface, input references, and output format.',
    '2. Load/read the real source data with the allowed tools before transforming it.',
    '3. Perform the smallest sufficient action using only allowed Larund tools.',
    '4. If a required connection is missing, stop with a blocker or ask before changing target surface.',
    '5. Verify the final result with read-back evidence before task.complete.',
    '',
    '## Verification checklist',
    ...spec.verification.map((item) => `- ${item}`),
  ].join('\n');

  return [
    '---',
    `name: ${JSON.stringify(spec.name)}`,
    `description: ${JSON.stringify(spec.description)}`,
    'version: "1.0.0"',
    'source: "bundled"',
    `categories: ${list(spec.categories)}`,
    `trigger: ${JSON.stringify(spec.triggers.join(' '))}`,
    `trigger_phrases: ${list(spec.triggers)}`,
    `when_to_use: ${list(spec.whenToUse)}`,
    `when_not_to_use: ${list(spec.whenNotToUse ?? [])}`,
    `allowed_tools: ${list([...new Set(spec.tools)])}`,
    `requires_connections: ${list(spec.connections ?? [])}`,
    'required_mcp_servers: []',
    `risk: ${JSON.stringify(spec.risk)}`,
    `verification_checklist: ${list(spec.verification)}`,
    'supports_automation: true',
    'supports_manual_run: true',
    'status: "enabled"',
    '---',
    '',
    body,
  ].join('\n');
}

export const GENERATED_BUNDLED_SKILL_FILES: string[] = SPECS.map(skillMarkdown);
