export const X_ENV_VARS = [
  'X_BEARER_TOKEN',
  'X_WRITE_ACCESS_TOKEN',
  'X_WRITE_ACCESS_TOKEN_SECRET',
  'X_CLIENT_ID',
  'X_CLIENT_SECRET',
  'X_API_KEY',
  'X_API_SECRET',
];

export const X_AUTH_GROUPS = [
  ['X_BEARER_TOKEN'],
  ['X_WRITE_ACCESS_TOKEN', 'X_WRITE_ACCESS_TOKEN_SECRET'],
];
