import type { ConnectionManifest } from '../types';
import { scaffoldTool } from '../scaffold';

function scaffoldManifest(
  id: string,
  name: string,
  description: string,
  envVars: string[],
  tools: Array<[string, string, ConnectionManifest['risk']]>,
): ConnectionManifest {
  return {
    id,
    name,
    description,
    auth: { type: envVars.length ? 'api_key' : 'custom', envVars },
    scaffold: true,
    risk: tools.some(([, , risk]) => risk === 'external_send') ? 'external_send' : 'external_write',
    tools: tools.map(([tool, toolDescription, risk]) => scaffoldTool(tool, toolDescription, risk ?? 'external_read')),
  };
}

// Manifest-only scaffolds: registered (so they appear in the UI as disabled),
// but not runnable until implemented + configured.
export const hubspotManifest: ConnectionManifest = {
  id: 'hubspot',
  name: 'HubSpot',
  description: 'CRM contacts, deals and companies (coming soon).',
  auth: { type: 'api_key', envVars: ['HUBSPOT_PRIVATE_APP_TOKEN'] },
  scaffold: true,
  risk: 'external_write',
  tools: [
    scaffoldTool('hubspot.search_contacts', 'Search contacts.', 'external_read'),
    scaffoldTool('hubspot.create_contact', 'Create a contact.', 'external_write'),
  ],
};

export const airtableManifest: ConnectionManifest = {
  id: 'airtable',
  name: 'Airtable',
  description: 'Bases, tables and records (coming soon).',
  auth: { type: 'api_key', envVars: ['AIRTABLE_TOKEN'] },
  scaffold: true,
  risk: 'external_write',
  tools: [
    scaffoldTool('airtable.list_records', 'List records.', 'external_read'),
    scaffoldTool('airtable.create_record', 'Create a record.', 'external_write'),
  ],
};

export const wordpressManifest: ConnectionManifest = {
  id: 'wordpress',
  name: 'WordPress',
  description: 'Posts and pages via REST API (coming soon).',
  auth: { type: 'api_key', envVars: ['WORDPRESS_SITE_URL', 'WORDPRESS_USERNAME', 'WORDPRESS_APP_PASSWORD'] },
  scaffold: true,
  risk: 'external_write',
  tools: [
    scaffoldTool('wordpress.list_posts', 'List posts.', 'external_read'),
    scaffoldTool('wordpress.create_post', 'Create a draft post.', 'external_write'),
  ],
};

export const moreScaffoldManifests: ConnectionManifest[] = [
  scaffoldManifest('discord', 'Discord', 'Guilds, channels and messages (coming soon).', ['DISCORD_BOT_TOKEN'], [
    ['discord.test_connection', 'Verify Discord bot token.', 'external_read'],
    ['discord.list_guilds', 'List guilds.', 'external_read'],
    ['discord.list_channels', 'List channels.', 'external_read'],
    ['discord.read_messages', 'Read messages.', 'external_read'],
    ['discord.send_message', 'Send a message.', 'external_send'],
  ]),
  scaffoldManifest('linear', 'Linear', 'Issues and teams (MCP available).', ['LINEAR_API_KEY'], [
    ['linear.test_connection', 'Verify Linear API key.', 'external_read'],
    ['linear.list_teams', 'List teams.', 'external_read'],
    ['linear.list_issues', 'List issues.', 'external_read'],
    ['linear.create_issue', 'Create an issue.', 'external_write'],
    ['linear.update_issue', 'Update an issue.', 'external_write'],
    ['linear.comment_issue', 'Comment on an issue.', 'external_write'],
  ]),
  scaffoldManifest('resend', 'Resend', 'Transactional email (coming soon).', ['RESEND_API_KEY'], [
    ['resend.test_connection', 'Verify Resend API key.', 'external_read'],
    ['resend.send_email', 'Send email.', 'external_send'],
    ['resend.get_domain', 'Get domain.', 'external_read'],
    ['resend.list_domains', 'List domains.', 'external_read'],
  ]),
  scaffoldManifest('sendgrid', 'SendGrid', 'Email delivery (coming soon).', ['SENDGRID_API_KEY'], [
    ['sendgrid.test_connection', 'Verify SendGrid API key.', 'external_read'],
    ['sendgrid.send_email', 'Send email.', 'external_send'],
    ['sendgrid.list_templates', 'List templates.', 'external_read'],
    ['sendgrid.get_template', 'Get template.', 'external_read'],
  ]),
  scaffoldManifest('supabase', 'Supabase', 'Projects, SQL and edge functions (MCP available).', ['SUPABASE_ACCESS_TOKEN'], [
    ['supabase.test_connection', 'Verify Supabase token.', 'external_read'],
    ['supabase.list_projects', 'List projects.', 'external_read'],
    ['supabase.get_project', 'Get project.', 'external_read'],
    ['supabase.execute_sql', 'Execute SQL.', 'external_write'],
    ['supabase.list_edge_functions', 'List edge functions.', 'external_read'],
    ['supabase.deploy_edge_function', 'Deploy edge function.', 'external_write'],
  ]),
  scaffoldManifest('vercel', 'Vercel', 'Projects and deployments (MCP available).', ['VERCEL_TOKEN'], [
    ['vercel.test_connection', 'Verify Vercel token.', 'external_read'],
    ['vercel.list_projects', 'List projects.', 'external_read'],
    ['vercel.list_deployments', 'List deployments.', 'external_read'],
    ['vercel.get_deployment', 'Get deployment.', 'external_read'],
    ['vercel.create_deployment', 'Create deployment.', 'external_write'],
    ['vercel.set_env_var', 'Set environment variable.', 'external_write'],
  ]),
  scaffoldManifest('stripe', 'Stripe', 'Customers, invoices and balances (coming soon).', ['STRIPE_SECRET_KEY'], [
    ['stripe.test_connection', 'Verify Stripe key.', 'external_read'],
    ['stripe.list_customers', 'List customers.', 'external_read'],
    ['stripe.list_invoices', 'List invoices.', 'external_read'],
    ['stripe.create_invoice_draft', 'Create invoice draft.', 'external_write'],
    ['stripe.retrieve_balance', 'Retrieve balance.', 'external_read'],
  ]),
  scaffoldManifest('meta-ads', 'Meta Ads', 'Ad accounts and campaign drafts (coming soon).', ['META_ACCESS_TOKEN'], [
    ['meta.test_connection', 'Verify Meta token.', 'external_read'],
    ['meta.list_ad_accounts', 'List ad accounts.', 'external_read'],
    ['meta.list_campaigns', 'List campaigns.', 'external_read'],
    ['meta.get_campaign_insights', 'Get campaign insights.', 'external_read'],
    ['meta.create_campaign_draft', 'Create campaign draft.', 'external_write'],
    ['meta.create_adset_draft', 'Create ad set draft.', 'external_write'],
    ['meta.create_ad_draft', 'Create ad draft.', 'external_write'],
    ['meta.publish_campaign', 'Publish campaign.', 'external_send'],
  ]),
  scaffoldManifest('instagram-business', 'Instagram Business', 'Media and insights (coming soon).', ['META_ACCESS_TOKEN', 'INSTAGRAM_BUSINESS_ACCOUNT_ID'], [
    ['instagram.test_connection', 'Verify Instagram Business config.', 'external_read'],
    ['instagram.get_account', 'Get account.', 'external_read'],
    ['instagram.get_media', 'Get media.', 'external_read'],
    ['instagram.get_insights', 'Get insights.', 'external_read'],
    ['instagram.create_media_container', 'Create media container.', 'external_write'],
    ['instagram.publish_media', 'Publish media.', 'external_send'],
  ]),
  scaffoldManifest('facebook-pages', 'Facebook Pages', 'Page posts and insights (coming soon).', ['META_ACCESS_TOKEN', 'META_PAGE_ID'], [
    ['facebook_pages.test_connection', 'Verify Facebook Pages config.', 'external_read'],
    ['facebook_pages.list_pages', 'List pages.', 'external_read'],
    ['facebook_pages.get_page_insights', 'Get page insights.', 'external_read'],
    ['facebook_pages.create_post', 'Create page post.', 'external_send'],
  ]),
  scaffoldManifest('google-ads', 'Google Ads', 'Campaigns and performance (coming soon).', ['GOOGLE_ADS_DEVELOPER_TOKEN', 'GOOGLE_ADS_CUSTOMER_ID'], [
    ['google_ads.test_connection', 'Verify Google Ads config.', 'external_read'],
    ['google_ads.list_customers', 'List customers.', 'external_read'],
    ['google_ads.list_campaigns', 'List campaigns.', 'external_read'],
    ['google_ads.get_campaign_performance', 'Get campaign performance.', 'external_read'],
    ['google_ads.create_draft_campaign', 'Create campaign draft.', 'external_write'],
    ['google_ads.apply_mutation', 'Apply mutation.', 'external_send'],
  ]),
  scaffoldManifest('ga4', 'Google Analytics 4', 'Analytics reports (coming soon).', ['GA4_PROPERTY_ID'], [
    ['ga4.test_connection', 'Verify GA4 config.', 'external_read'],
    ['ga4.run_report', 'Run report.', 'external_read'],
    ['ga4.realtime_report', 'Realtime report.', 'external_read'],
    ['ga4.get_metadata', 'Get metadata.', 'external_read'],
  ]),
  scaffoldManifest('search-console', 'Google Search Console', 'Search performance (coming soon).', ['SEARCH_CONSOLE_SITE_URL'], [
    ['search_console.test_connection', 'Verify Search Console config.', 'external_read'],
    ['search_console.list_sites', 'List sites.', 'external_read'],
    ['search_console.query_search_analytics', 'Query search analytics.', 'external_read'],
    ['search_console.inspect_url', 'Inspect URL.', 'external_read'],
  ]),
  scaffoldManifest('jira', 'Jira / Atlassian', 'Projects and issues (coming soon).', ['ATLASSIAN_EMAIL', 'ATLASSIAN_API_TOKEN', 'ATLASSIAN_SITE_URL'], [
    ['jira.test_connection', 'Verify Jira config.', 'external_read'],
    ['jira.list_projects', 'List projects.', 'external_read'],
    ['jira.search_issues', 'Search issues.', 'external_read'],
    ['jira.create_issue', 'Create issue.', 'external_write'],
    ['jira.update_issue', 'Update issue.', 'external_write'],
    ['jira.comment_issue', 'Comment issue.', 'external_write'],
  ]),
  scaffoldManifest('trello', 'Trello', 'Boards, lists and cards (coming soon).', ['TRELLO_API_KEY', 'TRELLO_TOKEN'], [
    ['trello.test_connection', 'Verify Trello config.', 'external_read'],
    ['trello.list_boards', 'List boards.', 'external_read'],
    ['trello.list_lists', 'List lists.', 'external_read'],
    ['trello.list_cards', 'List cards.', 'external_read'],
    ['trello.create_card', 'Create card.', 'external_write'],
    ['trello.update_card', 'Update card.', 'external_write'],
  ]),
  scaffoldManifest('mailchimp', 'Mailchimp', 'Audiences and campaigns (coming soon).', ['MAILCHIMP_API_KEY', 'MAILCHIMP_SERVER_PREFIX'], [
    ['mailchimp.test_connection', 'Verify Mailchimp key.', 'external_read'],
    ['mailchimp.list_audiences', 'List audiences.', 'external_read'],
    ['mailchimp.list_campaigns', 'List campaigns.', 'external_read'],
    ['mailchimp.create_campaign_draft', 'Create campaign draft.', 'external_write'],
    ['mailchimp.send_campaign', 'Send campaign.', 'external_send'],
  ]),
  scaffoldManifest('brevo', 'Brevo', 'Contacts and email campaigns (coming soon).', ['BREVO_API_KEY'], [
    ['brevo.test_connection', 'Verify Brevo key.', 'external_read'],
    ['brevo.list_contacts', 'List contacts.', 'external_read'],
    ['brevo.create_contact', 'Create contact.', 'external_write'],
    ['brevo.send_transactional_email', 'Send transactional email.', 'external_send'],
    ['brevo.create_campaign_draft', 'Create campaign draft.', 'external_write'],
  ]),
  scaffoldManifest('shopify', 'Shopify', 'Products and orders (coming soon).', ['SHOPIFY_SHOP_DOMAIN', 'SHOPIFY_ADMIN_ACCESS_TOKEN'], [
    ['shopify.test_connection', 'Verify Shopify token.', 'external_read'],
    ['shopify.list_products', 'List products.', 'external_read'],
    ['shopify.get_order', 'Get order.', 'external_read'],
    ['shopify.update_product', 'Update product.', 'external_write'],
    ['shopify.create_discount', 'Create discount.', 'external_write'],
  ]),
  scaffoldManifest('netlify', 'Netlify', 'Sites and deploys (coming soon).', ['NETLIFY_AUTH_TOKEN'], [
    ['netlify.test_connection', 'Verify Netlify token.', 'external_read'],
    ['netlify.list_sites', 'List sites.', 'external_read'],
    ['netlify.list_deploys', 'List deploys.', 'external_read'],
    ['netlify.create_deploy', 'Create deploy.', 'external_write'],
    ['netlify.list_forms', 'List forms.', 'external_read'],
    ['netlify.list_hooks', 'List hooks.', 'external_read'],
  ]),
  scaffoldManifest('cloudflare', 'Cloudflare', 'DNS and Workers (coming soon).', ['CLOUDFLARE_API_TOKEN'], [
    ['cloudflare.test_connection', 'Verify Cloudflare token.', 'external_read'],
    ['cloudflare.list_zones', 'List zones.', 'external_read'],
    ['cloudflare.list_dns_records', 'List DNS records.', 'external_read'],
    ['cloudflare.create_dns_record', 'Create DNS record.', 'external_write'],
    ['cloudflare.update_worker', 'Update Worker.', 'external_write'],
  ]),
  scaffoldManifest('sentry', 'Sentry', 'Projects and issues (coming soon).', ['SENTRY_AUTH_TOKEN', 'SENTRY_ORG', 'SENTRY_PROJECT'], [
    ['sentry.test_connection', 'Verify Sentry token.', 'external_read'],
    ['sentry.list_projects', 'List projects.', 'external_read'],
    ['sentry.list_issues', 'List issues.', 'external_read'],
    ['sentry.get_issue', 'Get issue.', 'external_read'],
    ['sentry.resolve_issue', 'Resolve issue.', 'external_write'],
  ]),
  scaffoldManifest('langsmith', 'LangSmith', 'LLM traces and projects (coming soon).', ['LANGSMITH_API_KEY'], [
    ['langsmith.test_connection', 'Verify LangSmith key.', 'external_read'],
    ['langsmith.list_projects', 'List projects.', 'external_read'],
    ['langsmith.list_traces', 'List traces.', 'external_read'],
    ['langsmith.get_trace', 'Get trace.', 'external_read'],
    ['langsmith.analyze_recent_errors', 'Analyze recent errors.', 'external_read'],
  ]),
  scaffoldManifest('figma', 'Figma', 'Files, nodes and comments (MCP available).', ['FIGMA_ACCESS_TOKEN'], [
    ['figma.test_connection', 'Verify Figma token.', 'external_read'],
    ['figma.get_file', 'Get file.', 'external_read'],
    ['figma.get_nodes', 'Get nodes.', 'external_read'],
    ['figma.list_comments', 'List comments.', 'external_read'],
    ['figma.post_comment', 'Post comment.', 'external_write'],
  ]),
  scaffoldManifest('canva', 'Canva', 'Designs and exports (MCP available).', ['CANVA_ACCESS_TOKEN'], [
    ['canva.test_connection', 'Verify Canva token.', 'external_read'],
    ['canva.list_designs', 'List designs.', 'external_read'],
    ['canva.get_design', 'Get design.', 'external_read'],
    ['canva.create_design', 'Create design.', 'external_write'],
    ['canva.export_design', 'Export design.', 'external_read'],
  ]),
  scaffoldManifest('webflow', 'Webflow', 'CMS and publishing (coming soon).', ['WEBFLOW_ACCESS_TOKEN', 'WEBFLOW_SITE_ID'], [
    ['webflow.test_connection', 'Verify Webflow token.', 'external_read'],
    ['webflow.list_sites', 'List sites.', 'external_read'],
    ['webflow.list_collections', 'List collections.', 'external_read'],
    ['webflow.list_items', 'List items.', 'external_read'],
    ['webflow.create_item', 'Create item.', 'external_write'],
    ['webflow.update_item', 'Update item.', 'external_write'],
    ['webflow.publish_site', 'Publish site.', 'external_send'],
  ]),
  scaffoldManifest('framer', 'Framer', 'Sites and projects (coming soon).', ['FRAMER_API_KEY'], [
    ['framer.test_connection', 'Verify Framer key.', 'external_read'],
    ['framer.list_sites', 'List sites.', 'external_read'],
    ['framer.list_projects', 'List projects.', 'external_read'],
    ['framer.get_site', 'Get site.', 'external_read'],
    ['framer.update_content', 'Update content.', 'external_write'],
  ]),
  scaffoldManifest('microsoft-365', 'Microsoft 365', 'Outlook, OneDrive and Calendar (coming soon).', ['MICROSOFT_CLIENT_ID', 'MICROSOFT_CLIENT_SECRET', 'MICROSOFT_TENANT_ID'], [
    ['microsoft.test_connection', 'Verify Microsoft Graph config.', 'external_read'],
    ['outlook.search_email', 'Search email.', 'external_read'],
    ['outlook.draft_email', 'Draft email.', 'external_write'],
    ['outlook.send_email', 'Send email.', 'external_send'],
    ['onedrive.search_files', 'Search files.', 'external_read'],
    ['onedrive.get_file', 'Get file.', 'external_read'],
    ['calendar.search_events', 'Search events.', 'external_read'],
    ['calendar.create_event', 'Create event.', 'external_write'],
  ]),
  scaffoldManifest('higgsfield', 'Higgsfield', 'Creative generation via MCP.', ['HIGGSFIELD_MCP_URL'], [
    ['higgsfield.mcp_tools', 'Approved Higgsfield MCP tools.', 'external_write'],
  ]),
];
